services:
  base:
    build:
      context: .
      dockerfile: Dockerfile.base
    image: ghcr.io/zhaw-pm4-gamified-fitness-app/github-runner-base:latest
  main:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/zhaw-pm4-gamified-fitness-app/github-runner:latest
    volumes:
      - ~/ZHAW/PM4/gamified-fitness:/workspace
    command: ["tail", "-f", "/dev/null"]
